// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicMenuGroup,
  DefaultMenuGroupProps
} from "./plasmic/inprodi_design_system/PlasmicMenuGroup";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface MenuGroupProps extends Omit<DefaultMenuGroupProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultMenuGroupProps altogether and have
// total control over the props for your component.
export interface MenuGroupProps extends DefaultMenuGroupProps {}

function MenuGroup_(props: MenuGroupProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicMenuGroup to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicMenuGroup are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all MenuGroupProps here, but feel free
  // to do whatever works for you.

  return <PlasmicMenuGroup root={{ ref }} {...props} />;
}

const MenuGroup = React.forwardRef(MenuGroup_);
export default MenuGroup;
